Kokkos_StdFileSpace.o: $(KOKKOS_CPP_DEPENDS) $(KOKKOS_RESILIENCE_PATH)/src/resilience/impl/Kokkos_StdFileSpace.cpp
	$(CXX) $(KOKKOS_CPPFLAGS) $(KOKKOS_CXXFLAGS) $(CXXFLAGS) -c $(KOKKOS_RESILIENCE_PATH)/src/resilience/impl/Kokkos_StdFileSpace.cpp
Kokkos_ExternalIOInterface.o: $(KOKKOS_CPP_DEPENDS) $(KOKKOS_RESILIENCE_PATH)/src/resilience/impl/Kokkos_ExternalIOInterface.cpp
	$(CXX) $(KOKKOS_CPPFLAGS) $(KOKKOS_CXXFLAGS) $(CXXFLAGS) -c $(KOKKOS_RESILIENCE_PATH)/src/resilience/impl/Kokkos_ExternalIOInterface.cpp

ifeq ($(KOKKOS_INTERNAL_USE_CUDA), 1)
Kokkos_ResCuda_Impl.o: $(KOKKOS_CPP_DEPENDS) $(KOKKOS_RESILIENCE_PATH)/src/resilience/Cuda/Kokkos_ResCuda_Impl.cpp
	$(CXX) $(KOKKOS_CPPFLAGS) $(KOKKOS_CXXFLAGS) $(CXXFLAGS) -c $(KOKKOS_RESILIENCE_PATH)/src/resilience/Cuda/Kokkos_ResCuda_Impl.cpp
Kokkos_ResCudaSpace.o: $(KOKKOS_CPP_DEPENDS) $(KOKKOS_RESILIENCE_PATH)/src/resilience/Cuda/Kokkos_ResCudaSpace.cpp
	$(CXX) $(KOKKOS_CPPFLAGS) $(KOKKOS_CXXFLAGS) $(CXXFLAGS) -c $(KOKKOS_RESILIENCE_PATH)/src/resilience/Cuda/Kokkos_ResCudaSpace.cpp
endif

ifeq ($(KOKKOS_INTERNAL_USE_HDF5), 1)
Kokkos_HDF5Space.o: $(KOKKOS_CPP_DEPENDS) $(KOKKOS_RESILIENCE_PATH)/src/resilience/impl/Kokkos_HDF5Space.cpp
	$(CXX) $(KOKKOS_CPPFLAGS) $(KOKKOS_CXXFLAGS) $(CXXFLAGS) -c $(KOKKOS_RESILIENCE_PATH)/src/resilience/impl/Kokkos_HDF5Space.cpp
endif

